POST http://localhost:5002/api/linkedin-jobs/4160760417

###

GET http://localhost:5002/api/linkedin-jobs/4160760417

###

GET http://localhost:5001/api/github/projects
Content-Type: application/json

{
    "githubUsername": "yairnadler"
}

###

POST http://localhost:5001/api/github/projects
Content-Type: application/json

{
    "githubUsername": "yairnadler"
}

###

GET http://localhost:5001/api/github/projects/2
